INSERT INTO tb_movie_list (name) VALUES ('Suspense');
INSERT INTO tb_movie_list (name) VALUES ('Animation');

INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Get Out', 7.8, 2017, 'Terror, Thriller, Mystery', 'Prime Video', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Shutter Island', 8.2, 2018, 'Drama, Thriller, Mystery', 'Microsoft Store', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lAH2HXxIjRWOrFVjwhBSsNr7yGW.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Se7en', 8.6, 1995, 'Crime, Mystery, Thriller ', 'Google Play', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vBKObrRM3B62DmzBkJN0TnQqczt.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Memento', 8.4, 2000, 'Mystery, Thriller', 'Prime Video', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3jFQqn81xdYqNquQZtsu8PJBPiB.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Inception', 8.8, 2010, 'Action, Science Fiction, Adventure', 'Netflix', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Spireted Away', 8.6, 2001, 'Animation, Family, Fantasy', 'Max', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Howl's Moving Castle', 8.2, 2004, 'Animation, Adventure, Fantasy', 'Max', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/23hUJh7JdO23SpgUB5oiFDQk2wX.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('How To Train Your Dragon', 8.1, 2010, 'Animation, Adventure, Family, Fantasy', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sherek', 7.9, 2001, 'Animation, Adventure, Comedy, Family, Fantasy', 'Peacock', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Akira', 8.0, 1998, 'Animation, Action, Science Fiction', 'Crunchyroll', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/neZ0ykEsPqxamsX6o5QNUFILQrz.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');

INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 10, 4);